# baseURL = 'https://pedro-bernardo.github.io/blog'
languageCode = 'en-us'
title = 'Pedro Bernardo'
theme = 'archie'

pygmentsstyle = "github-dark"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
	mode="toggle" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "CTF Writeup and Tech Adventures Blog"
	mathjax = true # enable MathJax support
	katex = true # enable KaTeX support

[[params.social]]
name = "GitHub"
icon = "fa-brands fa-github"
url = "https://github.com/pedro-bernardo"

[[params.social]]
name = "Twitter"
icon = "fa-brands fa-twitter"
url = "https://x.com/bl4ck_pwn"

[[params.social]]
name = "LinkedIn"
icon = "fa-brands fa-linkedin"
url = "https://linked.in/in/pedro-bernardo"

[[params.social]]
name = "GoogleScholar"
icon = "fa fa-graduation-cap"
url = "https://scholar.google.com/citations?user=SDzErw0AAAAJ&hl=en"

[[menu.main]]
name = "CV"
url = "/"
weight = 4

[[menu.main]]
name = "Blog"
url = "/blog"
weight = 1

[[menu.main]]
name = "All posts"
url = "/blog/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3


[[module.mounts]]
source = 'static'
target = 'static'

[[module.mounts]]
source = 'assets/img'
target = 'static/img'

[[module.mounts]]
source = 'assets/pdf'
target = 'static/pdf'

[[module.mounts]]
source = 'assets/misc'
target = 'static/misc'