# baseURL = 'https://pedro-bernardo.github.io/blog'
languageCode = 'en-us'
title = 'Pedro Bernardo'
theme = 'archie'

pygmentsstyle = "github-dark"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
	mode="dark" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "CTF Writeup and Tech Adventures Blog"
	mathjax = true # enable MathJax support
	katex = true # enable KaTeX support

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://example.com"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://example.com"

[[params.social]]
name = "BlueSky"
icon = "bluesky"
url = "https://example.com"

[[menu.main]]
name = "CV"
url = "/"
weight = 4

[[menu.main]]
name = "Blog"
url = "/blog"
weight = 1

[[menu.main]]
name = "All posts"
url = "/blog/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3


[[module.mounts]]
source = 'static'
target = 'static'

[[module.mounts]]
source = 'assets/img'
target = 'static/img'

[[module.mounts]]
source = 'assets/code'
target = 'static/code'